feign:
  sentinel:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8989
        port: 8719  #每一个微服务与控制台传输数据使用的端口
      scg:
        fallback:
          content-type: application/json # 失败后返回的内容类型
#          response-status: 400  # 失败后返回的状态码
    gateway:
      routes:
        - id: baidu-route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq-route
          uri: https://www.qq.com
          predicates: #根据参数路由
            - Query=url,qq

        # 商品服务api接口
        - id: product-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-product
          # 断言 这里是根据路径匹配
          predicates:
            - Path=/api/product/**, /hello
          # 设置过滤器
          filters: # 设置路径过滤将/api替换为/renren-fast
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 优惠服务api接口
        - id: coupon-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-coupon
          # 断言 这里是根据路径匹配
          predicates:
            - Path=/api/coupon/**
          # 设置过滤器
          filters: # 设置路径过滤将/api替换为/renren-fast
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 第三方服务api接口
        - id: third-party-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-third-party
          # 断言 这里是根据路径匹配
          predicates:
            - Path=/api/thirdparty/**
          # 设置过滤器
          filters: # 设置路径过滤将/api替换为/renren-fast
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}

        # 会员服务api接口
        - id: member-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-member
          # 断言 这里是根据路径匹配
          predicates:
            - Path=/api/member/**
          # 设置过滤器
          filters: # 设置路径过滤将/api替换为/renren-fast
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 仓储服务api接口
        - id: ware-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-ware
          # 断言 这里是根据路径匹配
          predicates:
            - Path=/api/ware/**
          # 设置过滤器
          filters: # 设置路径过滤将/api替换为/renren-fast
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 人人api路由
        - id: admin-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://renren-fast
          # 断言 这里是根据路径匹配
          predicates:
            - Path=/api/**
          # 设置过滤器
          filters: # 设置路径过滤将/api替换为/renren-fast
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

        # 商城首页路由
        - id: sino-mall-host-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-product
          # 断言 这里是根据路径匹配
          predicates:
            - Host=sinomall.com,item.sinomall.com

        # 商品搜索入口路由
        - id: sino-mall-search-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-search
          # 断言 这里是根据路径匹配
          predicates:
            - Host=search.sinomall.com

        # 认证入口路由
        - id: sino-mall-auth-server-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-auth-server
          # 断言 这里是根据路径匹配
          predicates:
            - Host=auth.sinomall.com

        # 购物车入口路由
        - id: sino-mall-car-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-car
          # 断言 这里是根据路径匹配
          predicates:
            - Host=cart.sinomall.com

        # 购物车入口路由
        - id: sino-mall-order-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-order
          # 断言 这里是根据路径匹配
          predicates:
            - Host=order.sinomall.com

        # 购物车入口路由
        - id: sino-mall-member-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-member
          # 断言 这里是根据路径匹配
          predicates:
            - Host=member.sinomall.com

        # 购物车入口路由
        - id: sino-mall-seckill-route
          # lb:负载均衡 //xxx = 服务名
          uri: lb://sino-mall-seckill
          # 断言 这里是根据路径匹配
          predicates:
            - Host=seckill.sinomall.com