server:
  port: 20000
spring:
  application:
    name: sino-mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.199.130
    port: 6379
  session:
    store-type: redis
    timeout: 30m
sinomall:
  server:
    auth-domain: auth.sinomall.com
    index-domain: sinomall.com